# Generated by Django 5.2 on 2025-04-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом')], max_length=20),
        ),
    ]
